version: '3'
services:
        api:
                build: ./api
                # Команда, которая выполнится при старте сервиса
                command: npm run start
                # Указываем какие порты будут доступны снаружи
                ports:
                        # слева - порт хоста
                        # справа - порт внутри контейнера
                         - "3000:3000"

